version: '3.9'

services:
  laravel-app:
    build:
      context: ./..
      dockerfile: docker/Dockerfile
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - ./../backend:/var/www/html
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:7.0.14
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongodb:/data/db
    ports:
      - ${MONGO_HOST_PORT}:${MONGO_CONTAINER_PORT}

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    volumes:
      - redis_data:/data

volumes:
  mongodb:
  redis_data:
