version: '3.8'

services:
  laravel-app:
    build:
      context: ./..
      dockerfile: docker/Dockerfile
    container_name: backend
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - SESSION_DRIVER=file
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=${MONGO_CONTAINER_PORT}
      - CACHE_STORE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_CONTAINER_PORT}
    volumes:
      - ./../backend:/var/www/html
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    depends_on:
      - mongodb
      - redis
    command: sh -c "php artisan migrate:fresh || echo 'Migration failed'; php artisan db:seed || echo 'Seeding failed'; apache2-foreground"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./../database/mongo:/data/db
    ports:
      - ${MONGO_HOST_PORT}:${MONGO_CONTAINER_PORT}

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    volumes:
      - redis_data:/data

volumes:
  redis_data:
